### ISSUE TITLE
How to include with my composer autoload?

### ISSUE THREAD

**Issue by kennywyland** [sixty-nine/PHP_Word_Cloud#4]
I'm an experienced dev, but new to using composer. I've tried to add it to my composer.json, but composer can't find the package. 

I tried downloading it directly and including it, but without the autoload configuration, it's awkward to go through and require each of the classes.

How can I integrate this with composer so that it's downloaded and autoloaded?

**Comment by sixty-nine** [comment]
This package is not (will never be) completely finished and is not deployed to packagist.
To autoload the classes you still can:

1) Download the files in a specific directory of your project
2) Add the following to your composer.json (replace `<path to the downloaded files>` by the proper path):

```
    "autoload": {
        "psr-0": {
            "SixtyNine": "<path to the downloaded files>/src"
        }
    }
```

3) Run composer install to update the autoloader

**Comment by borys-p** [comment]
This package is more stable than a lot of code on Packagist, so I wouldn't hold it :-)

**Comment by sixty-nine** [comment]
I'm not very experienced with deploying code on packagist it would be great if you could help.

Also please check this other repo where everything has been rewritten and improved, but is tightly coupled with Symfony and Imagine: `sixty-nine/php-cloud`.
