### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by mal-tee** [sixty-nine/PHP_Word_Cloud#6]
Hello maintainer(s), 

I am a security researcher from the Institute of Application Security at TU Braunschweig, Germany. We discovered a (potential) security vulnerability in your project.

We would like to report this vulnerability to you in a responsible and ethical manner.
Therefore, we do not want to disclose any details of the vulnerability publicly until you have had a chance to review and fix it.

**Could you please let us know your prefered way of receiving security reports?**

You can contact us at ias-disclosure@tu-braunschweig.de or by replying to this issue.

Thank you for your attention and cooperation.

**Comment by sixty-nine** [comment]
Hello,

Thank you for your message.

I am not working on this project anymore.

I am aware there are problems with the examples (/demo) and the provided "backend" (/src/SixtyNine/WebSite). Those are provided essentially as an example of usage of the library (/src/SixtyNine/WordCloud).

I could imagine spending some time on this repo if there are problems in the library itself, but not on the examples.

Are the vulnerabilities in /src/SixtyNine/WordCloud?

**Comment by sixty-nine** [comment]
Hello,

Thank you for your message.

This repo is old and deprecated:

![image](https://github.com/sixty-nine/PHP_Word_Cloud/assets/398679/e86a0e81-4b7c-41b4-8a54-b06ed5435815)

Please see https://github.com/sixty-nine/php-cloud-lib
